# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krUrQlB33DPwPbRToP85999ywuRH4yBW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder



"""Importing Libaries."""

data=pd.read_csv('./sales_data.csv')#Importing dataset

load=data['online'].value_counts()#Grouping data based on label
gender=data['gender'].value_counts()
occupation=data['occupation'].value_counts()
print(data)

"""Description of data."""

plt.rcParams['figure.dpi'] = 150##Change display resolution of chart
plt.pie(load,labels=['Yes('+str(load[0])+')','No('+str(load[1])+')'])##Plot data to pie chart.
plt.title('Online shopping experience')
plt.show()
print(occupation.index)
plt.pie(occupation,labels=[t+'('+str(occupation[t])+')' for t in occupation.index])##Polt data to pie chart.
plt.title('Occupation')

groupdata=data[['education','house_val']].groupby(['education']).mean()
print(groupdata)
plt.plot(groupdata,'-bo')
plt.xlabel('Education')
plt.ylabel('house value($)')

groupdata=data[['house_val','online']].groupby(['online']).mean()
print(groupdata['house_val'])
plt.bar(groupdata.index, groupdata['house_val'],color=['red','green'])
plt.xlabel('Online')
plt.ylabel('Mean of house_val')

regiondata=data[['house_val','region']].groupby(['region']).mean()
plt.bar(regiondata.index,regiondata['house_val'])
plt.show()